storerevenuedata <- ts(read.csv("D:/Data/storerevenuedata.csv", header = T), start = c(2011,1),frequency = 12)
storerevenuedatatrain <- ts(storerevenuedata[1:36,],start = c(2011,1),frequency = 12)
test_data_actuals <- ts(storerevenuedata[37:43,],start = c(2014,1), frequency = 12)
plot(stl(storerevenuedatatrain, s.window = 12))
plot(acf(storerevenuedatatrain))
plot(pacf(storerevenuedatatrain))
library(car)
durbinwatsontest(lm(storerevenuedatatrain ~ 1))
install.packages("forecast")
library(forecast)
arimasfit1<-Arima(storerevenuedatatrain,order = c(0,0,0),seasonal = list(order = c(0,1,0),period = 12))
acf(arimasfit1$residuals)
pacf(arimasfit1$residuals)
summary(arimasfit1)
arimasfit2 <- Arima(storerevenuedatatrain,order = c(0,0,0),seasonal = list(order=c(1,1,0),period = 12))
acf(arimasfit2$residuals)
pacf(arimasfit2$residuals)
summary(arimasfit2)
plot(stl(arimasfit2$residuals, s.window = 12))
arimasfit3 <- Arima(storerevenuedatatrain,order = c(1,0,0),seasonal = list(order = c(0,1,0),period = 12),include.drift = T)
acf(arimasfit3$residuals)
pacf(arimasfit3$residuals)
summary(arimasfit3)
arimafitfinal <- Arima(storerevenuedatatrain,order = c(0,0,0),seasonal = list(order = c(1,1,0),period = 12),include.drift = T)
acf(arimafitfinal$residuals)
pacf(arimafitfinal$residuals)
summary(arimafitfinal)
arimafitauto <- auto.arima(storerevenuedatatrain)
summary(arimafitauto)
etssfit <- ets(storerevenuedatatrain)
etssfit
arimaresults <- forecast(arimafitfinal,h = 7);arimaresults
etssresults <- forecast(etssfit,h = 7);etssresults
accuracy(forecast(arimafitfinal,7),test_data_actuals)
accuracy(forecast(etssfit,7),test_data_actuals)
swd<- arimaresults <-forecast (arimafitfinal,h = 7);arimaresults
write.csv(swd,"arimaresults.csv",row.names = F)
swd<- etssresults <-forecast (etssfit,h = 7);etssresults
write.csv(swd,"etssresults.csv",row.names = F)
plot(1:7,test_data_actuals,type="l",ylm=c(47000000,63000000),main="Actuals (vs) Predicted",ylab="",xlab = "")
lines(1:7,arimaresults$mean,type='l',col=4,ylim=c(47000000,63000000))
lines(1:7,etssresults$mean,type='l',col=3,ylim=c(47000000,63000000))
legend("bottomright",legend = c("ARIMA","ETS"),col=c(4,3),lty = 1)